# <center> Numpy Basics </center>

 ***Let's get started  with our Numpy Assigment**

In [300]:
#import numpy module with alias np

import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [301]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
a = np.array([1,2,3])


In [302]:
# print a
a

array([1, 2, 3])

## Dimensions in Arrays

In [303]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([ [1,2,3], [4,5,6] ])
d = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ]) 


Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [304]:
#print dimentions of a,b, c and d

print('a dimension:',a.ndim)
print('b dimension:',b.ndim)
print('c dimension:',c.ndim)
print('d dimension:',d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [305]:
# print shape of each a,b ,c and d

print('shape of a:',a.shape)
print('shpae of b:',b.shape)
print('shape of c:',c.shape)
print('shape of d:',d.shape)

shape of a: ()
shpae of b: (3,)
shape of c: (2, 3)
shape of d: (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [306]:
# print data type of c and d

print(c.dtype)
print(d.dtype)

int64
int64


Lets check the type of our variable. To check type of any numpy variable use type() function 

In [307]:
#print type of a and b variable

print(type(a))
print(type(b))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [308]:
# Lets check length of array b, using len() function
len(b)

3

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [309]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array([l1])
l4 = np.array([l2])


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [310]:
#code here as instructed above

%timeit result = [x*y for x,y in zip(l1,l2)]


537 ns ± 30.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [311]:

%timeit l3 * l4


679 ns ± 25 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### Creating Numpy array

1. Using arrange() function <br>

In [312]:
#Create a numpy array using arange with 1 and 11 as parameter in it

np.arange(1,11,dtype='int')


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [313]:
# Create an array using arange passing 1,11 and 2 as parameter in iter

np.arange(1,11,2,dtype='int')


array([1, 3, 5, 7, 9])

2. Using eye Function <br>


In [314]:
# create numpy array using eye function with 3 as passed parameter

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3. Using zero function<br>


In [315]:
#create a numpy array using zero function with (3,2) as passed parameter

np.zeros((3,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

4. Using ones Function <br>

In [316]:
#create a numpy array using ones function with (3,2) as passed parameter

np.ones((3,2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

5. Using full Function<br>

In [317]:
#create a numpy array using full function with (3,2) and 2 as passed parameter

np.full((3,2),2)


array([[2, 2],
       [2, 2],
       [2, 2]])

6. Using diag function<br>

In [318]:
#create a numpy array using diag function passing a list [1,2,3,4,5]

np.diag([1,2,3,4,5])


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

 7. Using tile function<br>

In [319]:
# Create a numpy array v with [1,2,3] as its elements
v = np.array([1,2,3])


#Use tile function of numpy and pass v and (3,1) as its parametrs

np.tile(v,(3,1))


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

8. Using linspace Function<br>

In [320]:
# Create an array with 100 values between 1 and 50 using linspace

np.linspace(1,50,100)


array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

## Numpy Random numbers

In [321]:
# Generate one random number between 0 and 1 using numpy's random.rand() function.
import numpy as np
l= np.random.rand()

l

0.13859913807507773

In [322]:
type(l)

float

In [323]:
# so let say I want a random value between 2 and 50

np.random.randint(2,51)


6

In [324]:
#get an array as stated above

l1 = np.random.rand(3,3)
l1

array([[0.54083852, 0.41823512, 0.617263  ],
       [0.96054262, 0.29739044, 0.77600069],
       [0.51771236, 0.37410721, 0.09849036]])


## Numpy Reshape


In [325]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x= np.arange(16)

1. Reshaping 1-D to 2-D

In [326]:
# Reshape x with 2 rows and 8 columns
arr_2d = x.reshape(2,8)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])


2. Reshaping 1-D to 3-D array

In [327]:
# reshape x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:

arr_3d = x.reshape(2,4,2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [328]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

x = np.arange(1,17)
unknown_reshape = x.reshape(4,-1)
unknown_reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [329]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y= np.reshape(x,(2,4,-1))


# print y

print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [330]:
# Flattening y

arr_1d = y.reshape(-1)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])


## NumPy Array Indexing


In [331]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,18,2)

# print a
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [332]:
# Get third element in array a
print(a[2])

6


In [333]:
#Print 3rd, 5th, and 7th element in array a

a[[2,4,6]]


array([ 6, 10, 14])

Lets check the same for 2 D array

In [334]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = [[1,2,3],[4,5,6],[7,8,9]]


In [335]:
# print the 3rd element from the 3rd row of a

print(a[2][2])

9


Now lets check indexing for 3 D array 

In [336]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]


In [337]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

print(b[1][0][2])


9


In [338]:
# Print the second last element from the 2nd dim using negative indexing

print(b[0][1][-2])


5



## NumPy Array Slicing

1. **Array slicing in 1-D array.**

In [339]:
arr= np.arange(1,11)

arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [340]:
# Slice elements from 1st to 5th element from the following array:

arr[0:5]


array([1, 2, 3, 4, 5])

In [341]:
# Slice elements from index 5 to the end of the array:

arr[5:10]


array([ 6,  7,  8,  9, 10])

In [342]:
# Slice elements from the beginning to index 5 (not included):

arr[:5]


array([1, 2, 3, 4, 5])

In [343]:
# Slice from the index 3 from the end to index 1 from the end:


arr[-3:-1]


array([8, 9])

**STEP**

Use the step value to determine the step of the slicing:

In [344]:
# Print every other element from index 1 to index 7:

arr[1:7:2]


array([2, 4, 6])

In [345]:
# Return every other element from the entire array arr:

arr[0:10:2]


array([1, 3, 5, 7, 9])



Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**2. Array slicing in 2-D array.**

In [346]:
# Print array a

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [347]:
# From the third row, slice elements from index 1 to index 3 (not included) from array 'a'

a[2][1:]


array([8, 9])

In [348]:
# In array 'a' print index 2 from all the elements :

a[:,2]


array([3, 6, 9])

In [349]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:

a[:,1:]


array([[2, 3],
       [5, 6],
       [8, 9]])

## Numpy copy vs view

In [350]:
x1= np.array([0,1,2,3,4,5,6,7,8,9])

In [351]:
# assign x2 = x1

x2 = x1

In [352]:
#print x1 and x2

print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [353]:
# change 1st element of x2 as 10

x2[0] = 10


In [354]:
#Again print x1 and x2

print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [355]:
# Check memory share between x1 and x2

np.shares_memory(x1,x2)

True

In [356]:
# Create a view of x1 and store it in x3.
x3 = x1.view()


In [357]:
# Again check memory share between x1 and x3

np.shares_memory(x1,x3)


True

In [358]:
#Change 1st element of x3=100

x3[0] = 100

In [359]:
#print x1 and x3 to check if changes reflected in both

print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


Now its proved.

Lets see how **Copy()** function works

In [360]:
# Now create an array x4 which is copy of x1

x4= x1.copy()



In [361]:
# Change the last element of x4 as 900

x4[9] = 900



In [362]:
# print both x1 and x4 to check if changes reflected in both

print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


In [363]:
#Check memory share between x1 and x4

np.shares_memory(x1,x4)


False

## More operations on Numpy

**1. Applying conditions**


In [364]:
#print a
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We are going to use 'a' array for all our array condition operations.


In [365]:
# Check if every element in array a greater than 3 or not Using '>' notation

a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [366]:
# Get a list with all elements of array 'a' grater than 3

a[a>3]

array([4, 5, 6, 7, 8, 9])

In [367]:
# Get a list with all elements of array 'a' greater than 3 but less than 6

a[(a>3) & (a<6)]


array([4, 5])

In [368]:
# check if each elements in array 'x1' equals array 'x4' using '==' notation

x1 == x4


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

**2. Transposing array**

In [369]:
# Print Transpose of array 'a'
print(a.T)

#print array 'a'
print("-----------------")

print(a)


[[1 4 7]
 [2 5 8]
 [3 6 9]]
-----------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**3. hstack vs vstack function**

In [370]:
# stack x1 and x4 along columns.
vertival_stack = np.vstack((x1,x4))
vertival_stack

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [371]:
#stack x1 and x4 along rows
horizontal_stack = np.hstack((x1,x4))
horizontal_stack

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

In [372]:
arr1 = np.array([[1,2],
                 [3,4]])


arr2 = np.array([[5,6],
                 [7,8]])


##join arr1 and arr2 along columns using concatenate() function

arr_concatenate = np.concatenate([arr1,arr2],axis=1)
arr_concatenate

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [373]:
##join arr1 and arr2 along rows using concatenate() function

arr = np.concatenate([arr1,arr2],axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array


In [374]:
# append arr2 to arr1

result = np.append(arr1,arr2)
result

array([1, 2, 3, 4, 5, 6, 7, 8])

Lets use insert() function which Inserts values into array before specified index value

In [375]:
# Inserts values into array x1 before index 4 with elements of x4

result = np.insert(x1,4,x4)
result

array([100,   1,   2,   3, 100,   1,   2,   3,   4,   5,   6,   7,   8,
       900,   4,   5,   6,   7,   8,   9])

In [376]:
# delete 2nd element from array x2

delete_ = np.delete(x2,2)
print(delete_)

[100   1   3   4   5   6   7   8   9]


## Mathmatical operations on Numpy array


In [377]:
a= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])


In [378]:
# print trigonometric sin value of each element of a
sin_value = np.sin(a)
sin_value

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [379]:
# print trigonometric cos value of each element of a

cos_values = np.cos(a)
cos_values

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [380]:
# Print exponential value of each elements of a

exponential_values = np.exp(a)
exponential_values

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [381]:
# print total sum of elements of a
sum_values = np.sum(a)
print(sum_values)

45


In [382]:
# Print sum in array a column wise

columns_sum = np.sum(a,axis=1)
print(columns_sum)

[ 6 15 24]


In [383]:
# Print sum in array a row wise

rows_sum = np.sum(a,axis=0)
print(rows_sum)

[12 15 18]


In [384]:
# print median of array a

median_value = np.median(a)
print(median_value)

5.0


In [385]:
# print standard deviation of array a

std_dev = np.std(a)
print(std_dev)

2.581988897471611


In [386]:
# print the determinant of array a

det_value = np.linalg.det(a)
print(det_value)

-9.51619735392994e-16


In [387]:
# print the (multiplicative) inverse of array a

inverse_values = np.linalg.inv(a)
print(inverse_values)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [388]:
# Print the eigenvalues and right eigenvectors of array a.

eigenvalues,eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [389]:
# compute dot product of arr1 and arr2

dot_product = np.dot(arr1,arr2)
dot_product

array([[19, 22],
       [43, 50]])

In [390]:
#print largest element present in array a

max_value = np.max(a)
print(max_value)

9


In [391]:
#print index of largest element present in array a 

max_index = np.argmax(a)
max_index

np.int64(8)

In [392]:
# print sorted x4 array

sorted_arr = np.sort((x4))
sorted_arr

array([  1,   2,   3,   4,   5,   6,   7,   8, 100, 900])

In [393]:
# print indices of each sorted element in x4 array

elements_indices =  np.argsort(x4)
elements_indices

array([1, 2, 3, 4, 5, 6, 7, 8, 0, 9])

## Searching Arrays

In [394]:
# print the indexes where the value is 4 in array x1

print(np.where(x1 == 4))


(array([4]),)



You can check it by printing array x1

In [395]:
#print array x1

print(x1)

[100   1   2   3   4   5   6   7   8   9]


In [396]:
# Print the indexes where the values are even in array x1

print(np.where(x % 2 == 0))

(array([ 1,  3,  5,  7,  9, 11, 13, 15]),)


In [397]:
# Print x1 where x1 is greater than 5, also if number is less than 5 then replace it with 0

print(np.where(x1 > 5,x1,0))

[100   0   0   0   0   0   6   7   8   9]
